# /.github/ISSUE_TEMPLATE/config.yml _AedgeFork
contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/AedgeCoin/aedge-blockchain/discussions/new?category=support
  - about: Request a new feature or idea here
    name: Make a Request
    url: >-
      https://github.com/AedgeCoin/aedge-blockchain/discussions/new?category=ideas
